### ISSUE TITLE
Interface with ForecastFramework?

### ISSUE THREAD

**Issue by elray1** [reichlab/sarimaTD#11]

**Comment by katiehouse3** [comment]
I may be able to help you with this! I am working on implementing ForecastFramework with various models this summer

**Comment by elray1** [comment]
That would be great!  Let me know if you'd like to meet to talk through the code here or anything.

**Comment by katiehouse3** [comment]
Hi Evan--Just realized we can probably close this issue!

**Comment by elray1** [comment]
Yeah, awesome!  In order to make this official, if you're up for it do you think you could submit a pull request that:

- [ ] Adds yourself as a contributor in the Authors field of the package DESCRIPTION file
- [ ] Adds the R6 package to the Imports field of the package DESCRIPTION file
- [ ] Adds the ForecastFramework package to either the Imports or the Suggests field of the package DESCRIPTION file, depending on what you need to do to make building the package work
- [ ] Adds your implementation to a new .R file in the R folder, maybe named something like forecast-framework.R or sarimaTD-forecast-framework.R.  When you do this, it would be good to remove the explicit calls to require libraries at the top of the file and use the :: operator to identify package where functions/objects you're using live.  (I'm basing this comment on the SARIMATDModel.R file from your demo a while back)
- [ ] Depending on your motivation level, adds documentation in ROxygen format and the resulting man files.  Unfortunately it looks like documentation of R6 classes is not fully supported by ROxygen but I found these links with some discussions of how to get something going: https://stackoverflow.com/questions/45431845/documenting-r6-classes-and-methods-within-r-package-in-rstudio https://github.com/r-lib/R6/issues/3

**Comment by elray1** [comment]
Resolved by commit  34ae898
